app:
  name: bff
  image:
    repository: "onecx/onecx-iam-bff"
  operator:
    # Permission
    permission:
      enabled: true
      spec:
        permissions:
          user:
            admin-read: permission on all GET requests and POST search for admin operations
            admin-write: permission on all POST and PUT requests for admin operations
          role:
            admin-read: permission on all GET requests and POST search for admin operations
            admin-write: permission on all POST and PUT requests for admin operations
          provider:
            admin-read: permission on all GET requests and POST search for admin operations
            read: permission on all GET requests and POST search for user operations
          password:
            write: permission on PUT, POST, PATCH requests, where objects are saved or updated
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            defaultClientScopes: [ ocx-ia:all, ocx-pm:read ]